version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aprendices_frontend_app
    restart: unless-stopped
    ports:
      - "5173:5173"  # Cambia 5173 por el puerto de tu frontend (ej. 3000, 80, 8080)
    networks:
      - red-aprendices

networks:
  red-aprendices:
    external: true